server:
  port: 8092

spring:
  application:
    name: patient-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://Ayodya:Ayodya@cluster0.csn4fag.mongodb.net/HealthCareDB?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api/patients/v3/api-docs
  swagger-ui:
    path: /api/patients/swagger-ui.html


