server:
  port: 8080

spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/doctor_db}
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api/doctors/v3/api-docs
  swagger-ui:
    path: /api/doctors/swagger-ui.html


