POST http://localhost:8085/api/doctors
Content-Type: application/json

{
  "name": "Dr. Kamal Silva",
  "specialization": "General",
  "experience": 5
}


HTTP/1.1 403  - Forbidden
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
date: Thu, 16 Apr 2026 21:16:17 GMT
content-length: 0
connection: close
###
