server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://mysql:3306/payment_service
    username: root
    password: password
  data:
    mongodb:
      uri: mongodb://mongo:27017/payment_service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
