server:
  port: 8084
spring:
  application:
    name: telemedicine-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/telemedicine_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka:8761/eureka/}
springdoc:
  api-docs:
    path: /api/telemedicine/v3/api-docs
  swagger-ui:
    path: /api/telemedicine/swagger-ui.html
agora:
  appId: ${AGORA_APP_ID}
  appCertificate: ${AGORA_APP_CERTIFICATE}
jwt:
  secret: ${JWT_SECRET:your_actual_shared_secret_here}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG