apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: healthcare
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
