server:
  port: 8080

spring:
  application:
    name: payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api/payments/v3/api-docs
  swagger-ui:
    path: /api/payments/swagger-ui.html

stripe:
  apiKey: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}


